<?php
/**
 * HTS Inc.
 *
 * @category  HTS
 * @package   HTS_Marketplace
 * @author    HTS
 * @copyright Copyright (c) HTS Inc.
 */
?>
<?php
    $paramData = $this->getRequest()->getParams();
if (empty($paramData['loc'])) {
    $helper = $this->helper(\Hts\Marketplace\Helper\Data::class);
    $partner = $block->getProfileDetail();
    $locsearch = $partner['company_locality'];
    $paramData['loc'] = $locsearch;
}
?>
<div class="ht_mp_design">
    <?= $block->getChildHtml("marketplace_seller_top_block")?>
    <div class="ht-mp-collection-container">
        <iframe width="100%" height="550" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="//maps.google.com/maps?q=<?= $paramData['loc'];?>&amp;output=embed"></iframe>
        <br />
        <small>
            <a href="//maps.google.com/maps?q=<?= $this->escapeHtml($paramData['loc']);?>" class="ht_loc_inf"><?= $block->escapeHtml(__('View Larger Map')) ?></a>
        </small>
    </div>
</div>
