<?php
/**
 * HTS Inc.
 *
 * @category  HTS
 * @package   HTS_Marketplace
 * @author    HTS
 * @copyright Copyright (c) HTS Inc.
 */
$product_id=$this->getRequest()->getParam('id');
$getValues = $block->getGoogleoptimizerFieldsValues();
?>
<input type="hidden" name="google_experiment[experiment_script]" value="<?= /* @noEscape */ $getValues['experiment_script']?>">
<input type="hidden" name="google_experiment[code_id]" value="<?= /* @noEscape */ $getValues['code_id']?>">
