<?php
/**
 * HTS Inc.
 *
 * @category  HTS
 * @package   HTS_Marketplace
 * @author    HTS
 * @copyright Copyright (c) HTS Inc.
 */
/** @var $block \Hts\Marketplace\Block\Page\Notofications */
?>
<ul class="ht-mp__action-dropdown-menu ht-mp-dashboard-notifications-menu">
    <?php foreach ($block->getAllNotification() as $notification) {
      /* @noEscape */ echo $block->getNotificationInfo($notification);
    } ?>
    <li>
        <small>
            <a href="<?= $block->escapeUrl($block->getUrl('marketplace/account/notification'))?>">
                <?= $block->escapeHtml(__("View All"))?>
            </a>
        </small>
    </li>
</ul>
