<?php
/**
 * HTS Inc.
 *
 * @category  HTS
 * @package   HTS_Marketplace
 * @author    HTS
 * @copyright Copyright (c) HTS Inc.
 */
?>
<?php
    /** @var \Hts\Marketplace\Block\Adminhtml\Customer\Edit\Tab\Product $block */

    /** @var \Hts\Marketplace\Block\Adminhtml\Customer\Edit\Tab\Grid\Product $blockGrid */
    $blockGrid = $block->getBlockGrid();
    $gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getGridHtml(); ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Hts_Marketplace/js/seller/assign-products": {
                "selectedProducts": <?= /* @noEscape */ $block->getSellerAssignedProductsJson(); ?>,
                "gridJsObjectName": <?= /* @escapeNotVerified */ '"' . $gridJsObjectName . '"' ?: '{}'; ?>
            }
        }
    }
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>
<input type="hidden" name="sellerassignproid" id="in_adminassign_products" data-form-part="customer_form" value="" />
