<?php
/**
 * HTS Inc.
 *
 * @category  HTS
 * @package   HTS_Marketplace
 * @author    HTS
 * @copyright Copyright (c) HTS Inc.
 */
/** @var $block \Hts\Marketplace\Block\Page\Header */
$helper = $this->helper(\Hts\Marketplace\Helper\Data::class);
?>
<?php switch ($block->getShowPart()):
    case 'logo':
        ?>
        <a
            href="<?= /* @escapeNotVerified */ $block->escapeUrl($block->getBaseUrl()) ?>"
            class="ht-mp-logo">
            <span class="ht-mp-logo-img-wrapper">
                <img class="ht-mp-logo-img" src="<?= $block->escapeUrl($block->getSellerDashboardLogoSrc())?>" alt="<?= $block->escapeHtml(__('Seller Panel')) ?>"/>
            </span>
        </a>
        <?php
              break; ?>
    <?php case 'user':
        ?>
        <?php
        $logo = $block->getSellerLogo();
        $logo = $helper->getMediaUrl().'avatar/'.$logo;
        ?>
        <div class="ht-mp-user ht-mp__action-dropdown-wrap">
            <a
                href="#"
                onlick="return false;"
                class="ht-mp__action-dropdown"
                title="<?= $block->escapeHtml(__('My Account')) ?>"
                data-mage-init='{"dropdown":{}}'
                data-toggle="dropdown">
                <span class="ht-mp-seller-header-logo-wrapper">
                    <img class="ht-mp-seller-header-logo" src="<?= $block->escapeUrl($logo)?>" alt="<?= $block->escapeHtml(__('Seller Panel')) ?>"/>
                </span>
                <span class="ht-mp__action-dropdown-text">
                    <span class="ht-mp-user-account-text">
                        <span class="ht-mp-user-account-text-wrapper">
                            <?= $block->escapeHtml($block->getSellerShopName()); ?>
                        </span>
                    </span>
                </span>
            </a>
            <ul class="ht-mp__action-dropdown-menu">
                <li class="ht-mp-dropdown-menu-settings">
                    <a
                        href="<?= /* @escapeNotVerified */ $block->escapeUrl($block->getUrl('marketplace/account/editprofile')) ?>"
                        <?= /* @escapeNotVerified */ $block->escapeHtml($block->getUiId('user', 'account', 'settings'))?>
                        title="<?= $block->escapeHtml(__('Account Setting')) ?>">
                        <?= /* @escapeNotVerified */ $block->escapeHtml(__('Account Setting')) ?>
                    </a>
                </li>
                <li class="ht-mp-dropdown-menu-buyer">
                    <a
                        href="<?= /* @escapeNotVerified */ $block->escapeUrl($block->getUrl('customer/account')); ?>"
                        title="<?= $block->escapeHtml(__('Buyer Dashboard')); ?>"
                        target="_blank" class="store-front">
                        <?= /* @escapeNotVerified */ $block->escapeHtml(__('Buyer Dashboard')); ?>
                    </a>
                </li>
                <li class="ht-mp-dropdown-menu-logout">
                    <a
                        href="<?= /* @escapeNotVerified */ $block->escapeUrl($block->getUrl('customer/account/logout')) ?>"
                        class="ht-mp-account-logout"
                        title="<?= $block->escapeHtml(__('Logout')) ?>">
                        <?= /* @escapeNotVerified */ $block->escapeHtml(__('Logout')) ?>
                    </a>
                </li>
            </ul>
        </div>
        <?php
              break; ?>
    <?php case 'seller.notifications':
        ?>
        <?php $totalCount = $block->getAllNotificationCount(); ?>
        <div class="ht-mp-notification ht-mp__action-dropdown-wrap">
            <a
                onlick="return false;"
                href="#"
                class="ht-mp__action-dropdown"
                <?php if ($totalCount): ?> data-mage-init='{"dropdown":{}}' <?php endif; ?> >
                <span class="ht-mp-notification-icon"></span>
                <?php if ($totalCount): ?>
                    <?php if ($totalCount > 5): ?>
                        <span class="ht-mp-notification-count">5+</span>
                    <?php else: ?>
                        <span class="ht-mp-notification-count">
                            <?= $block->escapeHtml($totalCount); ?>
                        </span>
                    <?php endif; ?>
                <?php endif; ?>
            </a>
            <?php if ($totalCount): ?>
                <ul class="ht-mp__action-dropdown-menu">
                    <?php foreach ($block->getAllNotification() as $notification) {
                        echo $block->getNotificationInfo($notification);
                    } ?>
                    <li>
                        <small>
                            <a href="<?= $block->escapeUrl($block->getUrl('marketplace/account/notification'))?>">
                                <?= $block->escapeHtml(__("View All"))?>
                            </a>
                        </small>
                    </li>
                </ul>
            <?php endif; ?>
        </div>
        <?php
              break; ?>
    <?php case 'seller.home':
        ?>
        <div class="ht-mp-home ht-mp__action-dropdown-wrap">
            <a
                href="<?= $block->escapeUrl($block->getUrl(''))?>"
                class="ht-mp__action-dropdown">
            </a>
        </div>
        <?php
              break; ?>
    <?php case 'other':
        ?>
        <?= $block->getChildHtml(); ?>
        <?php
              break; ?>
<?php endswitch; ?>
