
<?php
/**
 * HTS Inc.
 *
 * @category  HTS
 * @package   HTS_Marketplace
 * @author    HTS
 * @copyright Copyright (c) HTS Inc.
 */
?>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "product-list-component": {
                    "component": "separateSellerProductList",
                    "template" : "Hts_Marketplace/separate-product-list"
                }
            }
        }
    }
}
</script>
