<?php
/**
 * HTS Inc.
 *
 * @category  HTS
 * @package   HTS_Marketplace
 * @author    HTS
 * @copyright Copyright (c) HTS Inc.
 */
if ($block->isShippineAvlForSeller()) { ?>
    <li data-ui-id="menu-hts-marketplace-shipsetting-menu" class="item-menu parent level-1">
        <strong class="ht-mp-submenu-group-title">
            <span><?= /* @noEscape */ __('Shipping Settings')?></span>
        </strong>
        <div class="ht-mp-submenu">
            <ul>
                <?= $block->getChildHtml();?>
            </ul>
        </div>
    </li>
<?php } ?>
